variables:
  DOCKER_DRIVER: overlay2

server:
  script:
    - docker build -t registry.heroku.com/karewa-server/server .
    - heroku container:push server -a karewa-server
    - heroku container:release server -a karewa-server
  only:
    - feat/suppliers-catalog
  except:
    - schedules
  tags:
    - helm

client:
  script:
    - docker build --target builder --force-rm -t registry.heroku.com/karewa-client/client:builder client && docker build --target release --force-rm -t registry.heroku.com/karewa-client/client client || docker build -t registry.heroku.com/karewa-client/client client
    - heroku container:push client -a karewa-client
    - heroku container:release client -a karewa-client
  only:
    - feat/suppliers-catalog
  except:
    - schedules
  tags:
    - helm
