variables:
  DOCKER_DRIVER: overlay2

server:
  script:
    - |
      heroku container:push web --app karewa-server \
      && heroku container:release web --app karewa-server
  only:
    - feat/suppliers-catalog
  except:
    - schedules
  tags:
    - helm

client:
  script:
    - |
      cd client \
      && docker build \
      --target builder \
      --cache-from registry.heroku.com/karewa-client/web:builder \
      -t registry.heroku.com/karewa-client/web:builder . \
      && \
      docker build \
        --target release \
        --cache-from registry.heroku.com/karewa-client/web \
        -t registry.heroku.com/karewa-client/web . \
      || \
      docker build \
        -t registry.heroku.com/karewa-client/web .
        gcloud docker -- push registry.heroku.com/karewa-client/web \
      && heroku container:push web --app karewa-client \
      && heroku container:release web --app karewa-client
  only:
    - feat/suppliers-catalog
  except:
    - schedules
  tags:
    - helm
