variables:
  DOCKER_DRIVER: overlay2

server:
  script:
    - |
      heroku container:push web --app karewa-server \
      && heroku container:release web --app karewa-server
  only:
    - feat/suppliers-catalog
  except:
    - schedules
  tags:
    - helm

client:
  script:
    - |
      cd client \
      && heroku container:push web --app karewa-client \
      && heroku container:release web --app karewa-client
  only:
    - feat/suppliers-catalog
  except:
    - schedules
  tags:
    - helm
