version:         "3"
services:
  app:
    image:       registry.gitlab.com/karewa/monitor
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://db:27017/monitor_db
    links:
      - db
    depends_on:
      - db
  db:
    image:       mongo
    volumes:
      - db:/data/db

volumes:
  db:
